remote_theme: chrisrhymes/bulma-clean-theme
title: malwr
subtitle: Home
layout: page
show_sidebar: true
show_menue: true
hide_hero: false
hero_text: malwr
hero_image: /7E356410-6840-465B-83E8-7DE1B5DF45AB.png
hero_height: is-fullwidth
hide_footer: true
